dev:
  push:
    - services:
        - docker
      stages:
        - name: test
          image: node:22-alpine
          script: |
            npm i -g pnpm
            pnpm install
            pnpm test

        - name: auto-tag
          image: cnbcool/git-auto-tag:latest
          settings:
            tagFormat: v\${version}
            dryRun: false
            blockWhenFail: false
            branch: $CNB_BRANCH
            repoUrlHttps: $CNB_REPO_URL_HTTPS
          exports:
            tag: NEW_TAG
        - name: show tag
          script: echo $NEW_TAG

        - name: sync to github
          imports:
            - https://cnb.cool/hututux/env/-/blob/main/github/Edward00Funny.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/Edward00Funny/exportx-upload.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}

        - name: docker build
          script: docker build -t exportxabfree/exportx-upload:dev .
        - name: docker login
          imports:
            - https://cnb.cool/hututux/env/-/blob/main/docker/exportxabfree.yml
          script: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        - name: docker push
          script: docker push exportxabfree/exportx-upload:dev
    - services:
        - docker
      stages:
        - name: build scf
          script: pnpm build:scf
        - name: run with tencentcom/coscli
          image: tencentcom/coscli
          imports:
            - https://cnb.cool/hututux/env/-/blob/main/s3/cos.yml
          script: |
            coscli config set --secret_id $TENCENT_SECRET_ID --secret_key $TENCENT_SECRET_KEY 
            coscli config add --init-skip=true -b $TENCENT_BUCKET -r $TENCENT_REGION
            coscli cp ./scf-package.zip cos://$TENCENT_BUCKET -r
 